apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-api-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/patientdb"
  SPRING_DATASOURCE_USERNAME: "patientuser"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SERVER_PORT: "8081"
  JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
