apiVersion: v1
kind: Service
metadata:
  name: patient-api-frontend-service
  namespace: default
  labels:
    app: patient-api
    component: frontend
spec:
  selector:
    app: patient-api
    component: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer  # ou NodeIP dependendo do cluster
