apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patient-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  ingressClassName: nginx
  rules:
  - host: patient-api.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: patient-api-service
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: patient-api-frontend-service
            port:
              number: 80
