apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
  labels:
    app: postgres
    role: database
spec:
  selector:
    app: postgres
    role: database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
