INSERT INTO cid10 (code, description, created_at, updated_at) VALUES
('A00', 'Cólera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A01', 'Febre tifoide e paratifoide', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A02', 'Outras infecções salmonela', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A03', 'Outras infecções intestinais bacterianas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A04', 'Infecções intestinais bacterianas de outras localizações', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A05', 'Outras intoxicações alimentares bacterianas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A06', 'Amebíase', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A07', 'Outras doenças intestinais protozoárias', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A08', 'Infecções intestinais virais e outras especificadas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A09', 'Diarréia e gastroenterite de origem infecciosa presumível', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A15', 'Tuberculose respiratória', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A16', 'Tuberculose de outras localizações', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A17', 'Tuberculose miliar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A18', 'Tuberculose de outros órgãos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A19', 'Tuberculose miliar não especificada', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A20', 'Peste', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A21', 'Tularemia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A22', 'Carbúnculo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A23', 'Brucelose', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A24', 'Mormo e melioidose', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);