INSERT INTO specialty (name, created_at, updated_at) VALUES
('Clínico Geral', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Psicólogo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nutricionista', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Enfermeiro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pediatria', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);